export const EXEC_ENV = process.env.EXEC_ENV;

export const READ_BACKEND_ENDPOINT = window.APP_CONFIG.READ_BACKEND_ENDPOINT;
export const WRITE_API_ENDPOINT = window.APP_CONFIG.WRITE_API_ENDPOINT;
export const GOOGLE_MAP_API_KEY = window.APP_CONFIG.GOOGLE_MAP_API_KEY;
