linters:

  BorderZero:
    enabled: false

  Indentation:
    width: 4

  HexLength:
    style: long

  PropertySortOrder:
    order: concentric

  StringQuotes:
    style: double_quotes

  LeadingZero:
    style: include_zero

  ZeroUnit:
    enabled: false

  EmptyLineBetweenBlocks:
    enabled: false
